### ISSUE TITLE
Minor errors

### ISSUE THREAD

**Issue by knguyen780** [OB2551/SEA-and-Schoof-algorithm#1]
This is a great project for Elliptic Cryptography. There are few minor errors that I found. After applying these fixes, the program can be run normally:
- in PolynomialsV2.py:
1. line 8: comment this, seem this line cause indent error
2. line 143: change into "return Polynomial(coefficients)"

- in EllipticCurve.py:
1. add "from QuotientRingV2 import *" 

- in CanonicalModularPolynomialsV2.py:
1. line 11: change into "phi = open("Modular Polynomials/Canonical/Phi" + str(l) + ".txt", "r")", to fix path error

**Comment by OB2551** [comment]
Hi,

Thank you for bringing this to my attention. It has been some time since I
have looked at this peoject, I'll have a look at this over the weekend.

Cheers.
